### ISSUE TITLE
how to move the level bar

### ISSUE THREAD

**Issue by lenz-cmd** [squarfiuznath/rank-card-neon-theme#1]
![Screenshot_20210530_172647](https://user-images.githubusercontent.com/84387230/120100962-cecbf080-c16d-11eb-9fcc-06c8d0aefc52.jpg)

how to move the level bar

**Comment by squarfiuznath** [comment]
You have to understand how canvas works with coordinates, if you want to center your bar I made another video with the centered bar (macOS card Theme)
